CINEMATICEXPERIENCE_VERSION = 1.0
CINEMATICEXPERIENCE_SITE = http://quitcoding.com/download
CINEMATICEXPERIENCE_SOURCE = Qt5_CinematicExperience_rpi_$(CINEMATICEXPERIENCE_VERSION).tgz
CINEMATICEXPERIENCE_DEPENDENCIES = qt5declarative qt5graphicaleffects

CINEMATICEXPERIENCE_INSTALL_STAGING = YES

define CINEMATICEXPERIENCE_CONFIGURE_CMDS
	(cd $(@D); $(TARGET_MAKE_ENV) $(HOST_DIR)/usr/bin/qmake)
endef

define CINEMATICEXPERIENCE_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D)
endef

#define CINEMATICEXPERIENCE_INSTALL_TARGET_CMDS
#	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) install INSTALL_ROOT=$(TARGET_DIR)
#	$(QT5_LA_PRL_FILES_FIXUP)
#endef

## this looks fishy, staging could be dropped or used to reorder things
#define CINEMATICEXPERIENCE_INSTALL_STAGING_CMDS
#	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) install INSTALL_ROOT=$(TARGET_DIR)
#	$(QT5_LA_PRL_FILES_FIXUP)
#endef
#
#
#define CINEMATICEXPERIENCE_INSTALL_TARGET_QMLS
#	cp -dpfr $(@D)/usr/qml/content $(TARGET_DIR)/usr/qml
#endef
#
#define CINEMATICEXPERIENCE_INSTALL_TARGET_CMDS
#	$(CINEMATICEXPERIENCE_INSTALL_TARGET_QMLS)
#endef

$(eval $(generic-package))
